name: auditpro_mobile
description: Auditor & Tax Filing mobile app for India.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.0.1
  intl: ^0.19.0
  shared_preferences: ^2.15.0
  fl_chart: ^0.68.0
  uuid: ^4.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
